CREATE TABLE IF NOT EXISTS reviews (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	pr_title VARCHAR(512) NOT NULL,
	pr_number INT NOT NULL,
	issues JSON NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX idx_pr_number (pr_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
